////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2024-2026 60East Technologies Inc., All Rights Reserved.
//
// This computer software is owned by 60East Technologies Inc. and is
// protected by U.S. copyright laws and other laws and by international
// treaties.  This computer software is furnished by 60East Technologies
// Inc. pursuant to a written license agreement and may be used, copied,
// transmitted, and stored only in accordance with the terms of such
// license agreement and with the inclusion of the above copyright notice.
// This computer software or any other copies thereof may not be provided
// or otherwise made available to any other person.
//
// U.S. Government Restricted Rights.  This computer software: (a) was
// developed at private expense and is in all respects the proprietary
// information of 60East Technologies Inc.; (b) was not developed with
// government funds; (c) is a trade secret of 60East Technologies Inc.
// for all purposes of the Freedom of Information Act; and (d) is a
// commercial item and thus, pursuant to Section 12.212 of the Federal
// Acquisition Regulations (FAR) and DFAR Supplement Section 227.7202,
// Government's use, duplication or disclosure of the computer software
// is subject to the restrictions set forth by 60East Technologies Inc..
//
////////////////////////////////////////////////////////////////////////////

package com.crankuptheamps.flink.util;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.UUID;

import org.apache.flink.annotation.Internal;

/**
 * Class used to generate consistent client names for a Flink job
 * even in the event of failures.
 */
@Internal
public class ClientNamePool {
  
    /** The delimiter between the client name, the counter, and the pool ID. */
    public static final String DELIMITER = "~";
    /** The String format that client names use. */
    public static final String CLIENT_NAME_FORMAT = "%s" + DELIMITER + "%d" + DELIMITER + "%s";
    /** The pool ID used. */
    public static final String CLIENT_NAME_POOL_ID = UUID.randomUUID().toString();

    /** The queue of available names. */
    private final Queue<String> names = new ArrayDeque<>();

    /** The amount of clients using a specific client name. */
    private int counter = 1;

    /**
     * Returns a client name by creating a new one or returning an existing name in the queue.
     *
     * @param clientName The base client name to apply the formatting to.
     */
    public String getClientName(String clientName) {
        if (names.peek() != null) {
            return names.poll();
        } else {
            String newClientName = String.format(CLIENT_NAME_FORMAT, clientName, counter, CLIENT_NAME_POOL_ID);
            counter++;
            return newClientName;
        }
    }

    /**
     * Adds a client name back to the queue.
     *
     * @param clientName The client name generated by {@link #getClientName(String)}.
     */
    public void returnClientName(String clientName) {
        names.add(clientName);
    }
}

